# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mrigal <mrigal@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/06 17:49:57 by mrigal            #+#    #+#              #
#    Updated: 2018/01/09 19:22:56 by lolivet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= libft.a
CC			= gcc
DEBUG		= yes
C_DFLAGS	= -Werror -Wextra -Wall
SRCS		= ft_atoi.c ft_bzero.c ft_isalnum.c ft_isalpha.c \
			ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c \
			ft_lstadd.c ft_lstdel.c ft_lstdelone.c ft_lstiter.c \
			ft_lstnew.c ft_lstmap.c ft_memalloc.c ft_memccpy.c \
			ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memdel.c \
			ft_memmove.c ft_memset.c ft_putchar.c ft_putchar_fd.c \
			ft_putendl.c ft_putendl_fd.c ft_putnbr.c ft_putnbr_fd.c \
			ft_putstr.c ft_putstr_fd.c ft_strcat.c ft_strchr.c \
			ft_strclr.c ft_strcmp.c ft_strcpy.c ft_strdel.c \
			ft_strdup.c ft_strequ.c ft_striter.c ft_striteri.c \
			ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c \
			ft_strmapi.c ft_strncat.c ft_strncmp.c ft_strncpy.c \
			ft_strnequ.c ft_strnew.c ft_strnstr.c ft_strrchr.c \
			ft_strsplit.c ft_strstr.c ft_strsub.c ft_strtrim.c \
			ft_tolower.c ft_toupper.c ft_print_words_tables.c \
			ft_sort_table.c ft_swap.c ft_strrev.c ft_foreach.c \
			ft_create_elem.c ft_sort_asc_tab.c ft_sort_desc_tab.c \
			ft_exit.c ft_sqrt_round.c
	
OBJS		= $(patsubst %.c, %.o, $(SRCS)) 

.PHONY: clean fclean re 			

all: $(NAME)
ifeq ($(DEBUG), yes)
	@echo "Makefile libft ok!"
else 
	@echo "Makefile libft fail!"
endif

$(NAME): $(OBJS)			
	ar rc $@ $^

%.o: %.c
	$(CC) $(C_FLAGS) $(C_DFLAGS) -c -o $@ $<

clean:
		rm -f $(OBJS)

fclean: clean
		rm -f $(NAME)

re: fclean all
